import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { CategoryListContextProvider } from "@/context/CategoryList";
import { UserNameContextProvider } from "@/context/UserName";
import LoginFormWrapper from "@/components/LoginFormWrapper";
import { DataProvider } from "@/context/Data";
import { MealContextProvider } from "@/context/MealContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider>
          <UserNameContextProvider>
            <CategoryListContextProvider>
              <MealContextProvider>
                <LoginFormWrapper>
                <Header/>
                <main className="px-20 py-10 max-lg:px-5 max-lg:py-8">
                    {children}
                </main>
                </LoginFormWrapper>
              </MealContextProvider>
            </CategoryListContextProvider>
          </UserNameContextProvider>
        </DataProvider>
      </body>
    </html>
  );
}
