import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CategoryListContextProvider } from "@/context/CategoryList";
import { UserNameContextProvider } from "@/context/UserName";
import LoginFormWrapper from "@/components/LoginFormWrapper";
import { DataProvider } from "@/context/Data";
import { MealContextProvider } from "@/context/MealContext";

const montserratFont = Montserrat({ 
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratFont.className} antialiased`}
      >
        <DataProvider>
          <UserNameContextProvider>
            <CategoryListContextProvider>
              <MealContextProvider>
                <LoginFormWrapper>
                <Header/>
                <main className="flex-1">
                    {children}
                </main>
                <Footer/>
                </LoginFormWrapper>
              </MealContextProvider>
            </CategoryListContextProvider>
          </UserNameContextProvider>
        </DataProvider>
      </body>
    </html>
  );
}
